### ISSUE TITLE
開発用でもよいのでサービス名を決める

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/5min#12]

**Comment by kuruma-gs** [comment]
- クラウドファクトリー
  - 工場っぽい感じ
- 2ndオフィス
  - 二つ目のオフィスのメンバー的な

もう少しツール感を出したバージョンも出すかな

**Comment by kamomc** [comment]
- Writers(ライターズ)
 - ライターがいっぱい集まるイメージ。
- Sikmin(シクミン)
 - コンテンツが製造されてく仕組みを提供することを表してみた。
- PipeWriter(パイプライター)
 - TypewriterとPipeを合わせた造語。パイプを流れるように記事ができるイメージを表してみた。
- TypeLine(タイプライン)
 - 記事がライン製造されるイメージを表してみた。

**Comment by Hozum** [comment]
* タクミー / Takme
　　仕事が出来る人（匠）をキープできるサービスだから
　　Take me, taxi みたいな感じでゴロもいいかなと
　　Take me と掛けて、「新しい職場に連れて行って」というこじつけも..　無理か。

キーワード一覧
名詞
　ワーカー
　ジョブ
　クラウド
　ソーシング
　フロー
　コネクト
　ライン
　リーチ
　ライフ
　ショクニン
　タクミ
　シゴト

動詞
　はっちゅう
　さがす
　つながる
　はたらく
　せいぞう

**Comment by kamomc** [comment]
- シゴトコネクト
 - 発注側と受注側をつなぐ
 - ワークフローを1直線につなぐ

**Comment by kuruma-gs** [comment]
- シゴトコネクト
で決定
